// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JoelHiltonFilmCollection.Migrations
{
    [DbContext(typeof(FilmCollectionContext))]
    partial class FilmCollectionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("Mission6_Cruz.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Director = "James Wan",
                            Edited = false,
                            Genre = "Horror",
                            LentTo = "Shir",
                            Notes = "Best movie!",
                            Rating = "PG-13",
                            ReleaseYear = 2010,
                            Title = "Insidious"
                        },
                        new
                        {
                            MovieId = 2,
                            Director = "John R. Leonetti",
                            Edited = false,
                            Genre = "Horror",
                            LentTo = "Shir",
                            Notes = "Incredible movie!",
                            Rating = "PG-13",
                            ReleaseYear = 2014,
                            Title = "Annabelle"
                        },
                        new
                        {
                            MovieId = 3,
                            Director = "Michael Chaves, James Wan",
                            Edited = false,
                            Genre = "Horror",
                            LentTo = "Shir",
                            Notes = "Amazing movie!",
                            Rating = "PG-13",
                            ReleaseYear = 2013,
                            Title = "The Conjuring"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
